version: "3.2"

services:
  db:
    env_file:
      - .env
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
    container_name: blog-db
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app:
    env_file:
      - .env
    build: .
    ports:
      - 9090:9090
    restart: always
    container_name: blog-app
